### ISSUE TITLE
About functional loss

### ISSUE THREAD

**Issue by san9569** [zhengyuf/STED-gaze#8]
Hi, I'm very thankful for sharing your code and this awesome project.

The coefficient of functional redirection loss is 20 that you empirically set from the paper.
I wonder why you set the coefficient of that to 200 in `config/ST-ED.json`.

Can you explain for me? Thank you

**Comment by zhengyuf** [comment]
Hello, thank you for your interest in our paper.
Actually, in equation 7 in the main paper, we have
<img width="400" alt="Screenshot 2021-03-04 at 15 12 04" src="https://user-images.githubusercontent.com/48751943/109976380-01e01e80-7cfc-11eb-9798-4d63f2a1ad21.png">
here, L_feature is set to 10. Then, in the final loss equation, L_F is again multiplyed by 20.
That's why the lambda for feature loss is 200.
Hope that answered your question.
